# Generated by Django 3.2.7 on 2021-09-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
